version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - ${OUT_PORT}:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql.conf
    command: 'postgres -c config_file="/etc/postgresql.conf"'
#  test_db:
#    image: postgres:latest
#    restart: always
#    env_file:
#      - .env
#    volumes:
#      - test_db:/var/lib/postgresql/test_data
#      - ./postgres.conf:/etc/postgresql.conf
#    command: 'postgres -c config_file="/etc/postgresql.conf"'
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: uvicorn main:app --workers ${WORKER_COUNT} --host 0.0.0.0 --port ${WEB_SERVER_PORT}
#    restart: always
#    ports:
#      - ${WEB_SERVER_PORT}:${WEB_SERVER_PORT}
#    env_file:
#      - .env
#    volumes:
#      - ./src/:/src/

volumes:
  db:
#  test_db:
#